- name: install payment
  hosts: payment
  become: yes
  tasks:
  - name: install python
    ansible.builtin.yum:
      name: "{{items}}"
      state: installed
    loop:
    - python36
    - gcc
    - python3-devel

  - name: check roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true

  - when: out.rc!=0
    name: create roboshop user
    become: yes
    ansible.builtin.user:
      name: roboshop

  - name: check /app directory exist or not
    anible.builtin.stat:
      path: /app
    register: directory

  - name: print directory status
    ansible.builtin.debug:
      msg: "output: {{directory}}"

  - when: directory.stat.exists == False
    name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

